// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Segfy.Infrastructure.Persistence.Context;

#nullable disable

namespace Segfy.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.17");

            modelBuilder.Entity("segfy.Domain.Entities.Apolice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeSegurado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroApolice")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ramo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NumeroApolice")
                        .IsUnique();

                    b.ToTable("Apolices");
                });

            modelBuilder.Entity("segfy.Domain.Entities.HistoricoSinistros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("SinistroId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatusAnterior")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusNovo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SinistroId");

                    b.ToTable("HistoricoSinistros");
                });

            modelBuilder.Entity("segfy.Domain.Entities.Sinistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApoliceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataSinistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoNegativa")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroSinistro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ValorAprovado")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorSolicitado")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApoliceId");

                    b.HasIndex("NumeroSinistro")
                        .IsUnique();

                    b.ToTable("Sinistros");
                });

            modelBuilder.Entity("segfy.Domain.Entities.HistoricoSinistros", b =>
                {
                    b.HasOne("segfy.Domain.Entities.Sinistro", "Sinistro")
                        .WithMany("Historicos")
                        .HasForeignKey("SinistroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sinistro");
                });

            modelBuilder.Entity("segfy.Domain.Entities.Sinistro", b =>
                {
                    b.HasOne("segfy.Domain.Entities.Apolice", "Apolice")
                        .WithMany("Sinistros")
                        .HasForeignKey("ApoliceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apolice");
                });

            modelBuilder.Entity("segfy.Domain.Entities.Apolice", b =>
                {
                    b.Navigation("Sinistros");
                });

            modelBuilder.Entity("segfy.Domain.Entities.Sinistro", b =>
                {
                    b.Navigation("Historicos");
                });
#pragma warning restore 612, 618
        }
    }
}
